### ISSUE TITLE
Start position is always 0,0

### ISSUE THREAD

**Issue by excelant100** [mcolella14/python_ghost_cursor#9]
Firstly, I am very thankful for transplanting ghost-cursor to python. It works like a charm and does exactly what I tell it to do.

But, the Start position of cursor.move or click is always 0,0. I want to randomize this, where can I set that?

I tried to page.mouse.move to random coordinates, but since I am scrolling. The movement done by page.mouse is useless and the cursor spawns back to 0,0.

**Comment by mcolella14** [comment]
You should be able to pass in a `start` argument to the `create_cursor` function. This argument should be a `dict` with keys of `x` and `y`, which represents the desired starting coordinates. You should be able to use it like this: 
```python
origin = {
    'x': 100,
    'y': 200
}
cursor = create_cursor(page, start=origin)
```

You could randomize those coordinate values, and I think that'll solve your problem if I'm understanding correctly. Hope this helps!

**Comment by excelant100** [comment]
Thank you for this quick answer, yeah I believe what you wrote make sense and I've tried it out like so:

 ```
await stealth_async(page)

    ranX = random.randint(0,page.viewport_size['width'])
    ranY = random.randint(0,page.viewport_size['height'])
    print(ranX, ranY)
    origin = {"x": ranX,"y":ranY }
    cursor = create_cursor(page,origin)
    await install_mouse_helper(page)
    await page.goto('https://yahoo.com/')
    await page.wait_for_timeout(3000)
    await page.goto('https://www.google.com')
```

     I will let this script in case some would need it in the future, but I must say it is working half-half. What I mean by that is that when the bot go to a new website. The cursor still spawn at the top left of the screen, but when I scroll, it spawns back at a random location of the screen. Weird!
     
     
    Also I would like to ask you about a interesting feature I've found about. It is called random_move(). I've read that it 
    allows the mouse to move freely and there is no parameter to share. Weirdly, it does not work? Maybe you could 
    explain me more in details about it. If it is not working or something, I can maybe PR. looks simple to do!

**Comment by mcolella14** [comment]
Ah yeah I'm not too sure how to prevent it from snapping to 0,0 on page navigation, but I'm not sure if it matters too much from a fingerprinting perspective. The cursor still has the last position and will snap back to that immediately, so if the site is listening to the `mousemove` event, it should still show the first movement on the new page as being at that last coordinate. Not entirely positive of that though.

And yeah I couldn't get the `random_move` feature to work with Playwright, but feel free to make a PR if you figure it out!

**Comment by excelant100** [comment]
Yeah I managed to make it work, but I am not sure the code is well written either way. I'll PR the code once I get home! Thank you!
